# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecbyapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housespec',
            name='ldk_ac_cooling_efficiency',
            field=models.CharField(choices=[('I', '（い）エアコン'), ('RO', '（ろ）エアコン'), ('HA', '（は）エアコン'), ('None', 'エネルギー消費効率区分を指定しない')], default='I', help_text='主居室におけるルームエアコンディショナー冷房のエネルギー消費効率の区分を指定します。', max_length=2, verbose_name='エネルギー消費効率区分：主居室'),
        ),
        migrations.AlterField(
            model_name='housespec',
            name='ldk_ac_heating_efficiency',
            field=models.CharField(choices=[('I', '（い）エアコン'), ('RO', '（ろ）エアコン'), ('HA', '（は）エアコン'), ('None', 'エネルギー消費効率区分を指定しない')], default='I', help_text='主居室ルームエアコンディショナー暖房のエネルギー消費効率区分を指定します。', max_length=4, verbose_name='エネルギー消費効率区分：主居室'),
        ),
        migrations.AlterField(
            model_name='housespec',
            name='oth_ac_cooling_efficiency',
            field=models.CharField(choices=[('I', '（い）エアコン'), ('RO', '（ろ）エアコン'), ('HA', '（は）エアコン'), ('None', 'エネルギー消費効率区分を指定しない')], default='I', help_text='他居室におけるルームエアコンディショナー冷房のエネルギー消費効率の区分を指定します。', max_length=2, verbose_name='エネルギー消費効率区分：他居室'),
        ),
        migrations.AlterField(
            model_name='housespec',
            name='oth_ac_heating_efficiency',
            field=models.CharField(choices=[('I', '（い）エアコン'), ('RO', '（ろ）エアコン'), ('HA', '（は）エアコン'), ('None', 'エネルギー消費効率区分を指定しない')], default='I', help_text='他居室ルームエアコンディショナー暖房のエネルギー消費効率区分を指定します。', max_length=4, verbose_name='エネルギー消費効率区分：他居室'),
        ),
        migrations.AlterField(
            model_name='housespec',
            name='water_heater_type',
            field=models.CharField(choices=[('GasClassic', 'ガス従来型給湯機（給湯専用型）'), ('GasLatentHeatRecovery', 'ガス潜熱回収型給湯機（給湯専用型）'), ('OilClassic', '石油従来型給湯機（給湯専用型）'), ('OilLatentHeatRecovery', '石油潜熱回収型給湯機（給湯専用型）'), ('ElectricHeater', '電気ヒーター式給湯機（給湯専用型）'), ('ElectricHeatPump', 'CO2冷媒電気ヒートポンプ給湯機（給湯専用型）'), ('Hybrid', '電気ヒートポンプ・ガス併用型給湯機（給湯専用型）'), ('Cogeneration', 'コージェネレーション'), ('Other', 'その他の給湯設備機器'), ('NotUsed', '給湯熱源機を設置しない')], default='ElectricHeatPump', help_text='給湯熱源機の種類を選択して下さい。「給湯設備機器を設置しない」を選択した場合、「標準設備機器」を想定して一次エネルギー消費量が計算されます。', max_length=31, verbose_name='給湯熱源種類（給湯専用型）'),
        ),
    ]
