# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecbyapi', '0002_auto_20180616_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housespec',
            name='gasoil_water_heater_jis_efficiency',
            field=models.DecimalField(decimal_places=1, default=83.6, help_text='モード熱効率[%]（燃料がガス・石油の場合）、エネルギー消費効率[%]（燃料がガスの場合）、熱効率[%]（燃料が石油の場合）を小数点以下1桁まで入力します。', max_digits=3, verbose_name='給湯機効率（ガス・石油の場合）'),
        ),
        migrations.AlterField(
            model_name='housespec',
            name='heating_water_heater_jis_efficiency',
            field=models.DecimalField(decimal_places=1, default=87.0, help_text='給湯・温水暖房一体型給湯機暖房部の熱効率[%]を小数点以下1桁まで入力します。', max_digits=3, verbose_name='給湯温水暖房機暖房部の効率[%]'),
        ),
        migrations.AlterField(
            model_name='housespec',
            name='integrated_water_heater_type',
            field=models.CharField(choices=[('IntegratedGasClassic', 'ガス従来型給湯温水暖房機（給湯・温水暖房一体型）'), ('IntegratedGasLatentHeatRecovery', 'ガス潜熱回収型給湯温水暖房機（給湯・温水暖房一体型）'), ('IntegratedOil', '石油従来型給湯温水暖房機（給湯・温水暖房一体型）'), ('IntegratedOilLatentHeatRecovery', '石油潜熱回収型給湯温水暖房機（給湯・温水暖房一体型）'), ('IntegratedElectricHeater', '電気ヒーター式給湯温水暖房機（給湯・温水暖房一体型）'), ('Hybrid_Gas', '暖房部：電気ヒートポンプ・ガス、給湯部：ガス（給湯・温水暖房一体型）'), ('Hybrid_Hybrid', '暖房部：電気ヒートポンプ・ガス、給湯部：電気ヒートポンプ・ガス（給湯・温水暖房一体型）'), ('Gas_Hybrid', '暖房部：ガス、給湯部：電気ヒートポンプ・ガス（給湯・温水暖房一体型）'), ('Cogeneration', 'コージェネレーション'), ('Other', 'その他の給湯設備機器'), ('NotUsed', '給湯熱源機を設置しない')], default='IntegratedGasLatentHeatRecovery', help_text='給湯熱源機の種類を選択して下さい。「給湯設備機器を設置しない」を選択した場合、「標準設備機器」を想定して一次エネルギー消費量が計算されます。', max_length=31, verbose_name='給湯熱源種類（給湯・温水暖房一体型）'),
        ),
    ]
