# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecbyapi', '0003_auto_20180617_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housespec',
            name='ldk_cooling_type',
            field=models.CharField(choices=[('RoomAirConditioningCooling', 'エアコン'), ('OtherCoolingDevice', 'その他の冷房設備機器等'), ('ElectricHeatPumpCentralCooling', 'ダクト式セントラル空調機'), ('NotInstalled', '冷房設備機器を設置しない')], default='RoomAirConditioningCooling', help_text='主居室の冷房設備を選択します。「ダクト式セントラル空調機」を選択すると、他居室の冷房と主・他居室の暖房設備も「ダクト式セントラル空調機」に設定されます。「冷房設備機器を設置しない」を選択した場合、「標準設備機器」を想定して一次エネルギー消費量が計算されます。', max_length=36, verbose_name='主居室の冷房'),
        ),
        migrations.AlterField(
            model_name='housespec',
            name='oth_cooling_type',
            field=models.CharField(choices=[('RoomAirConditioningCooling', 'エアコン'), ('OtherCoolingDevice', 'その他の冷房設備機器等'), ('NotInstalled', '冷房設備機器を設置しない')], default='RoomAirConditioningCooling', help_text='他居室の冷房設備を選択します。「ダクト式セントラル空調機」を選択は、主居室の冷房から行って下さい。「冷房設備機器を設置しない」を選択した場合、「標準設備機器」を想定して一次エネルギー消費量が計算されます。', max_length=36, verbose_name='他居室の冷房'),
        ),
    ]
