# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pecbyapi', '0004_auto_20180617_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housespec',
            old_name='hotwater_heat_source_efficiency',
            new_name='hotwater_heating_source_efficiency',
        ),
        migrations.RenameField(
            model_name='housespec',
            old_name='hotwater_heat_source_name',
            new_name='hotwater_heating_source_name',
        ),
        migrations.RenameField(
            model_name='housespec',
            old_name='hotwater_heat_source_pipe',
            new_name='hotwater_heating_source_pipe',
        ),
        migrations.RenameField(
            model_name='housespec',
            old_name='hotwater_heat_source_saving_input',
            new_name='hotwater_heating_source_saving_input',
        ),
        migrations.RenameField(
            model_name='housespec',
            old_name='hotwater_heat_source_type',
            new_name='hotwater_heating_source_type',
        ),
    ]
