# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecbyapi', '0007_auto_20180621_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housespec',
            name='hotwater_heating_source_efficiency',
        ),
        migrations.AddField(
            model_name='housespec',
            name='hotwater_heating_source_efficiency_GasClassic',
            field=models.DecimalField(decimal_places=1, default=81.0, help_text='温水暖房熱源機（ガス従来型熱源機）のJIS効率（定格能力におけるエネルギー消費効率）を、小数点以下1桁まで入力します。', max_digits=3, verbose_name='温水暖房熱源機（ガス従来型熱源機）JIS効率[%]'),
        ),
        migrations.AddField(
            model_name='housespec',
            name='hotwater_heating_source_efficiency_GasLatentHeatRecovery',
            field=models.DecimalField(decimal_places=1, default=87.0, help_text='温水暖房熱源機（ガス潜熱回収型熱源機）のJIS効率（定格能力におけるエネルギー消費効率）を、小数点以下1桁まで入力します。', max_digits=3, verbose_name='温水暖房熱源機（ガス潜熱回収型熱源機）JIS効率[%]'),
        ),
        migrations.AddField(
            model_name='housespec',
            name='hotwater_heating_source_efficiency_OilClassic',
            field=models.DecimalField(decimal_places=1, default=82.0, help_text='温水暖房熱源機（石油熱源機）のJIS効率（定格能力におけるエネルギー消費効率）を、小数点以下1桁まで入力します。', max_digits=3, verbose_name='温水暖房熱源機（石油熱源機）JIS効率[%]'),
        ),
    ]
