# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-30 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecbyapi', '0009_auto_20180629_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housespec',
            name='gasoil_water_heater_jis_efficiency_GasClassic_Mode',
            field=models.DecimalField(decimal_places=1, default=70.4, help_text='ガス従来型給湯機（給湯専用型もしくは給湯温水暖房機の給湯部）のモード熱効率[%]を小数点以下1桁まで入力します。', max_digits=3, verbose_name='ガス従来型給湯機のモード熱効率[%]'),
        ),
        migrations.AlterField(
            model_name='housespec',
            name='gasoil_water_heater_jis_efficiency_GasClassic_Other',
            field=models.DecimalField(decimal_places=1, default=70.4, help_text='ガス従来型給湯機（給湯専用型もしくは給湯温水暖房機の給湯部）のエネルギー消費効率[%]を小数点以下1桁まで入力します。', max_digits=3, verbose_name='ガス従来型給湯機のエネルギー消費効率[%]'),
        ),
        migrations.AlterField(
            model_name='housespec',
            name='gasoil_water_heater_jis_efficiency_GasLatentHeatRecovery_Mode',
            field=models.DecimalField(decimal_places=1, default=83.6, help_text='ガス潜熱回収型給湯機（給湯専用型もしくは給湯温水暖房機の給湯部）のモード熱効率[%]を小数点以下1桁まで入力します。', max_digits=3, verbose_name='ガス潜熱回収型給湯機のモード熱効率[%]）'),
        ),
        migrations.AlterField(
            model_name='housespec',
            name='gasoil_water_heater_jis_efficiency_GasLatentHeatRecovery_Other',
            field=models.DecimalField(decimal_places=1, default=83.6, help_text='ガス潜熱回収型給湯機（給湯専用型もしくは給湯温水暖房機の給湯部）のエネルギー消費効率[%]を小数点以下1桁まで入力します。', max_digits=3, verbose_name='ガス潜熱回収型給湯機のエネルギー消費効率[%]'),
        ),
        migrations.AlterField(
            model_name='housespec',
            name='gasoil_water_heater_jis_efficiency_OilClassic_Mode',
            field=models.DecimalField(decimal_places=1, default=77.9, help_text='石油従来型給湯機（給湯専用型もしくは給湯温水暖房機の給湯部）のモード熱効率[%]を小数点以下1桁まで入力します。', max_digits=3, verbose_name='石油従来型給湯機のモード熱効率[%]'),
        ),
        migrations.AlterField(
            model_name='housespec',
            name='gasoil_water_heater_jis_efficiency_OilClassic_Other',
            field=models.DecimalField(decimal_places=1, default=77.9, help_text='石油従来型給湯機（給湯専用型もしくは給湯温水暖房機の給湯部）の熱効率[%]を小数点以下1桁まで入力します。', max_digits=3, verbose_name='石油従来型給湯機の熱効率[%]'),
        ),
        migrations.AlterField(
            model_name='housespec',
            name='gasoil_water_heater_jis_efficiency_OilLatentHeatRecovery_Mode',
            field=models.DecimalField(decimal_places=1, default=81.9, help_text='石油潜熱回収型給湯機（給湯専用型もしくは給湯温水暖房機の給湯部）のモード熱効率[%]を小数点以下1桁まで入力します。', max_digits=3, verbose_name='石油潜熱回収型給湯機のモード熱効率[%]'),
        ),
        migrations.AlterField(
            model_name='housespec',
            name='gasoil_water_heater_jis_efficiency_OilLatentHeatRecovery_Other',
            field=models.DecimalField(decimal_places=1, default=81.9, help_text='石油潜熱回収型給湯機（給湯専用型もしくは給湯温水暖房機の給湯部）の熱効率[%]を小数点以下1桁まで入力します。', max_digits=3, verbose_name='石油潜熱回収型給湯機の熱効率[%]'),
        ),
    ]
