# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-30 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecbyapi', '0010_auto_20180730_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='housespec',
            name='calc_done',
            field=models.BooleanField(default=True, verbose_name='一次エネルギー消費量計算結果更新日時'),
        ),
    ]
