# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-01 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecbyapi', '0011_housespec_calc_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housespec',
            name='calc_done',
            field=models.BooleanField(default=False, verbose_name='一次エネルギー消費量計算結果更新日時'),
        ),
    ]
