# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-03 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecbyapi', '0012_auto_20180801_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='housespec',
            name='resE_C',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='housespec',
            name='resE_H',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='housespec',
            name='resE_L',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='housespec',
            name='resE_M',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='housespec',
            name='resE_SC',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='housespec',
            name='resE_SH',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='housespec',
            name='resE_SL',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='housespec',
            name='resE_SM',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='housespec',
            name='resE_ST',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='housespec',
            name='resE_SV',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='housespec',
            name='resE_SW',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='housespec',
            name='resE_T',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='housespec',
            name='resE_V',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='housespec',
            name='resE_W',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='housespec',
            name='resGenerateByCG',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='housespec',
            name='resGenerateByPV',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='housespec',
            name='resReduceByPV',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='housespec',
            name='resSellByPV',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
