# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-03 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecbyapi', '0013_auto_20180803_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='housespec',
            name='resErrMessage',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
