# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-02 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecbyapi', '0015_auto_20180902_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housespec',
            name='resErrMessage',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
